# This is a basic workflow to help you get started with Actions

name: Testing Flutter Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Pages Repo 
        uses: actions/checkout@v3
        with: 
          path: src
          repository: princestha/princestha.github.io
          token: ${{ secrets.BOT_TOKEN}}
      - name: Checkout Flutter Repo 
        uses: actions/checkout@v3
        with: 
          path: portfolio
          repository: princestha/portfolio-flutter
          token: ${{ secrets.BOT_TOKEN}}
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: 3.7.1
          cache: true
  
      - name: Testing Flutter
        working-directory: ${GITHUB_WORKSPACE}/portfolio
        run: |
          ls
          flutter pub get
          flutter build web
          cd ..
          cp -r portfolio/build/web/. src/
          cp -r build/web/. ../
      
      - name: Checkout and commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated web"
          git push       

      # - name: Commit and push changes
      #   run: |
      #     cp -a flutterapp/. webapp
      #     cd webapp
      #     echo pwd
      #     git config user.name princestha
      #     git config user.email prasitshrestha@gmail.com
      #     git add .
      #     git commit -m "generated"
      #     git push
